<?php

namespace Millesime\Definition;

use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;

class CompilerConfiguration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('millesime');

        $rootNode
            ->children()
                ->scalarNode('name')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('version')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->arrayNode('authors')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('name')->end()
                            ->scalarNode('email')->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('distrib')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('name')->end()
                            ->scalarNode('stub')->end()
                            ->booleanNode('autoexec')
                                ->defaultTrue()
                            ->end()
                            ->arrayNode('finder')
                                ->children()
                                    ->arrayNode('in')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('depth')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('date')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('name')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('notName')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('contains')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('notContains')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('path')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('notPath')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('size')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('exclude')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->arrayNode('addVCSPattern')
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->booleanNode('directories')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('files')
                                        ->defaultTrue()
                                    ->end()
                                    ->booleanNode('ignoreDotFiles')
                                        ->defaultTrue()
                                    ->end()
                                    ->booleanNode('ignoreVCS')
                                        ->defaultTrue()
                                    ->end()
                                    ->booleanNode('sortByName')
                                        ->defaultTrue()
                                    ->end()
                                    ->booleanNode('sortByType')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('sortByAccessedTime')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('sortByChangedTime')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('sortByModifiedTime')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('followLinks')
                                        ->defaultFalse()
                                    ->end()
                                    ->booleanNode('ignoreUnreadableDirs')
                                        ->defaultTrue()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
